INSERT INTO reward (name, description, expiry_date, img_url, created_by, modified_by)
VALUES
('Free T-shirt', 'Get a branded T-shirt', '2024-12-31', 'http://example.com/tshirt.jpg', 'system', 'system'),
('Coffee Mug', 'Claim a stylish coffee mug', '2024-12-31', 'http://example.com/mug.jpg', 'system', 'system'),
('Notebook', 'A5 size notebook', '2024-12-31', 'http://example.com/notebook.jpg', 'system', 'system'),
('Pen Set', 'Premium pen set', '2024-12-31', 'http://example.com/pen.jpg', 'system', 'system'),
('Water Bottle', 'Stainless steel bottle', '2024-12-31', 'http://example.com/bottle.jpg', 'system', 'system'),
('Gift Card', 'Amazon gift card worth $10', '2024-12-31', 'http://example.com/giftcard.jpg', 'system', 'system'),
('Bluetooth Speaker', 'Portable speaker', '2024-12-31', 'http://example.com/speaker.jpg', 'system', 'system'),
('Earphones', 'Wired earphones', '2024-12-31', 'http://example.com/earphones.jpg', 'system', 'system'),
('Backpack', 'Trendy backpack', '2024-12-31', 'http://example.com/backpack.jpg', 'system', 'system'),
('Power Bank', '10000mAh power bank', '2024-12-31', 'http://example.com/powerbank.jpg', 'system', 'system'),
('USB Drive', '32GB USB drive', '2024-12-31', 'http://example.com/usb.jpg', 'system', 'system'),
('Desk Organizer', 'Keep your desk tidy', '2024-12-31', 'http://example.com/organizer.jpg', 'system', 'system'),
('Keychain', 'Custom keychain', '2024-12-31', 'http://example.com/keychain.jpg', 'system', 'system'),
('Sipper', 'Plastic sipper', '2024-12-31', 'http://example.com/sipper.jpg', 'system', 'system'),
('Lunch Box', 'Microwave safe lunch box', '2024-12-31', 'http://example.com/lunchbox.jpg', 'system', 'system'),
('Fitness Band', 'Track your steps', '2024-12-31', 'http://example.com/fitnessband.jpg', 'system', 'system'),
('Desk Calendar', '2024 desk calendar', '2024-12-31', 'http://example.com/calendar.jpg', 'system', 'system'),
('Sticky Notes', 'Pack of sticky notes', '2024-12-31', 'http://example.com/stickynotes.jpg', 'system', 'system'),
('Mobile Stand', 'Adjustable mobile stand', '2024-12-31', 'http://example.com/mobilestand.jpg', 'system', 'system'),
('Discount Coupon', 'Get 20% off on next purchase', '2024-12-31', 'http://example.com/coupon.jpg', 'system', 'system');